// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package toko_libur

import (
	"github.com/urfave/cli/v2"
)

// Injectors from wire.go:

func InitApplication(cCtx *cli.Context) (*Application, error) {
	appConfig := NewApplicationConfig(cCtx)
	report, err := NewReport(appConfig)
	if err != nil {
		return nil, err
	}
	application := NewApplication(appConfig, report)
	return application, nil
}
