// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	"github.com/gin-gonic/gin"
	"github.com/pdcgo/common_conf/common_concept"
	"github.com/pdcgo/tokopedia_lib/app/chat/api"
	"github.com/pdcgo/tokopedia_lib/app/chat/config"
	"github.com/pdcgo/tokopedia_lib/app/chat/group"
	"github.com/pdcgo/tokopedia_lib/app/chat/repo"
	"github.com/pdcgo/tokopedia_lib/app/chat/service"
)

// Injectors from wire.go:

func InitApplication(cfg *config.AppConfig) (*Application, error) {
	engine := gin.Default()
	apiSdk := CreateChatSdk(engine)
	coreEvent := common_concept.NewCoreEvent()
	server := CreateSocketIO(coreEvent)
	mainApi := api.NewMainApi()
	db := CreateSqliteDatabase(cfg)
	accountRepo := repo.NewAccountRepo(db)
	accountService := service.NewAccountService(accountRepo)
	accountApi := api.NewAccountApi(accountRepo, accountService)
	initConfig := config.NewInitConfig(cfg)
	driverGroup := group.NewDriverGroup()
	socketGroup := group.NewSocketGroup(coreEvent)
	chatGroup := group.NewChatGroup(coreEvent, initConfig, accountRepo, driverGroup, socketGroup)
	groupApi := api.NewGroupApi(db, chatGroup)
	chatApi := api.NewChatApi(initConfig, accountRepo, driverGroup)
	application := NewApplication(cfg, apiSdk, coreEvent, server, mainApi, accountApi, groupApi, chatApi)
	return application, nil
}
