// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package chat

import (
	"github.com/gin-gonic/gin"
	"github.com/pdcgo/common_conf/common_concept"
	"github.com/pdcgo/tokopedia_lib/app/chat/api"
	"github.com/pdcgo/tokopedia_lib/app/chat/config"
	"github.com/pdcgo/tokopedia_lib/app/chat/group"
	"github.com/pdcgo/tokopedia_lib/app/chat/helper"
	"github.com/pdcgo/tokopedia_lib/app/chat/repo"
	"github.com/pdcgo/tokopedia_lib/app/chat/service"
	"github.com/pdcgo/tokopedia_lib/lib/api_public"
)

// Injectors from wire.go:

func InitApplication(cfg *config.AppConfig) (*Application, error) {
	engine := gin.Default()
	apiSdk := CreateChatSdk(engine)
	coreEvent := common_concept.NewCoreEvent()
	server := CreateSocketIO(coreEvent)
	mainApi := api.NewMainApi()
	initConfig := config.NewInitConfig(cfg)
	db := CreateSqliteDatabase(cfg)
	accountRepo := repo.NewAccountRepo(db)
	driverGroup := group.NewDriverGroup()
	socketGroup := group.NewSocketGroup(cfg, coreEvent, server)
	chatGroup := group.NewChatGroup(server, initConfig, accountRepo, driverGroup, socketGroup)
	accountService := service.NewAccountService(initConfig, coreEvent, accountRepo, driverGroup, chatGroup)
	accountApi := api.NewAccountApi(server, accountService, initConfig)
	groupRepo := repo.NewGroupRepo(db)
	groupApi := api.NewGroupApi(db, initConfig, accountRepo, groupRepo, chatGroup)
	baseDriverApi := api.NewBaseDriverApi(initConfig, accountRepo, driverGroup)
	soundPlayer := helper.NewSoundPlayer(cfg)
	autoReplyConfig := config.NewAutoReplyConfig(cfg)
	chatService := service.NewChatService(coreEvent, initConfig, autoReplyConfig, accountRepo, socketGroup, soundPlayer)
	notificationService := service.NewNotificationService(coreEvent, initConfig, server, accountRepo, driverGroup, accountService)
	chatApi := api.NewChatApi(baseDriverApi, soundPlayer, chatService, notificationService)
	tokopediaApiPublic, err := api_public.NewTokopediaApiPublic()
	if err != nil {
		return nil, err
	}
	productApi := api.NewProductApi(tokopediaApiPublic)
	stickerApi := api.NewStickerApi(baseDriverApi)
	autoReplyApi := api.NewAutoReplyApi(autoReplyConfig)
	application := NewApplication(cfg, apiSdk, coreEvent, server, mainApi, accountApi, groupApi, chatApi, productApi, stickerApi, autoReplyApi)
	return application, nil
}
