// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package autochat

import (
	"github.com/pdcgo/common_conf/pdc_application"
)

// Injectors from wire.go:

func InitApplication(base pdc_application.BaseApplication) (*Application, error) {
	autochatMessage, err := NewAutochatMessage(base)
	if err != nil {
		return nil, err
	}
	autochatConfig, err := NewAutochatConfig(base)
	if err != nil {
		return nil, err
	}
	application := NewApplication(base, autochatMessage, autochatConfig)
	return application, nil
}
